version: '3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: angelikade/foodgram_backend:latest
    env_file:
      - ./.env
    volumes:
      - ../static:/app/static/
      - ../media:/app/media/recipes/
    depends_on:
      - db

  frontend:
    image: angelikade/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/build/
    depends_on:
      - db

  nginx:
    image: nginx:1.22.1
    volumes:
      - ../static:/var/html/static/
      - ../media:/var/html/media/recipes/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
